# Generated by Django 4.1.5 on 2023-01-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
