# Generated by Django 4.1.5 on 2023-01-21 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photo_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
